name: release

on: [deployment]

jobs:
  release:
    name: Deploy to nuget gallery
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: "${{ secrets.NUGET_API_KEY }}"
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: build package
        run: ./build.sh package

      - name: Upload nuget package
        run: |
          cd artifacts
          dotnet nuget push Gauge.CSharp.Lib*.nupkg -k $NUGET_API_KEY -s https://www.nuget.org/api/v2/package